export const FIND_CONTACTS_REQUEST = 'FIND_CONTACTS_REQUEST';
export const FIND_CONTACTS_SUCCESS = 'FIND_CONTACTS_SUCCESS';
export const FIND_CONTACTS_FAILURE = 'FIND_CONTACTS_FAILURE';

export const DELETE_CONTACT_REQUEST = 'DELETE_CONTACT_REQUEST';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAILURE = 'DELETE_CONTACT_FAILURE';

export const FIND_CONTACT_REQUEST = 'FIND_CONTACT_REQUEST';
export const FIND_CONTACT_SUCCESS = 'FIND_CONTACT_SUCCESS';
export const FIND_CONTACT_FAILURE = 'FIND_CONTACT_FAILURE';

export const SAVE_CONTACT_REQUEST = 'SAVE_CONTACT_REQUEST';
export const SAVE_CONTACT_SUCCESS = 'SAVE_CONTACT_SUCCESS';
export const SAVE_CONTACT_FAILURE = 'SAVE_CONTACT_FAILURE';
